spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL}
  servlet:
    multipart:
      max-file-size: 50MB

frontend:
  url: ${FRONTEND_URL}

keycloak:
  url: ${Key}

springdoc:
  default-produces-media-type: application/json

application:
  file:
    uploads:
      media-output-path: ./uploads

